name: Linux Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
    - 'main'

defaults:
  run:
    shell: bash

permissions:
  checks: write
  contents: write
  statuses: write

env:
  BUILD_DIR:    ${{ github.workspace }}/build
  QT_VERSION:   6.2.*

jobs:
  build:
    runs-on:  ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version:      ${{ env.QT_VERSION }}
          host:         linux
          target:       desktop
          arch:         gcc_64
          dir:          ${{ runner.temp }}
          setup-python: false

      - name: Create build directory
        run:  mkdir -p ${{ env.BUILD_DIR }}

      - name: Build
        working-directory: ${{ env.BUILD_DIR }}
        run:  |
              cmake -DRUN_CLANG_TIDY=ON -DUNITTESTS_EXTRA_ARGS="--gtest_output=xml:unittests.xml" -DUNITTESTS_COVERAGE=ON -S ..
              cmake --build .

      - name: Install gcovr
        run:  sudo apt-get -y install gcovr

      - name: Unittests
        working-directory: ${{ env.BUILD_DIR }}
        run: |
             ctest -C Debug --output-on-failure --verbose
             gcovr -r ${{ github.workspace }} -x coverage.cobertura.xml .

      - name: Unittests Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Backend unittests
          working-directory: ${{ env.BUILD_DIR }}
          path: src/backend/unittests.xml
          reporter: java-junit

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./**/*.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: false
          output: both

      - name: Prepare artifacts
        working-directory: ${{ env.BUILD_DIR }}
        run:  |
              mv src/liv .
              tar -cvf liv.tar liv

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux executable
          path: ${{ env.BUILD_DIR }}/liv.tar
