name: Linux Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
    - 'main'

defaults:
  run:
    shell: bash

env:
  BUILD_DIR:    ${{ github.workspace }}/build
  QT_VERSION:   6.2.*
  ARTIFACT:     liv

jobs:
  build:
    runs-on:  ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version:      ${{ env.QT_VERSION }}
          host:         linux
          target:       desktop
          arch:         gcc_64
          dir:          ${{ runner.temp }}
          setup-python: false

      - name: Create build directory
        run:  mkdir -p ${{ env.BUILD_DIR }}

      - name: Build
        working-directory: ${{ env.BUILD_DIR }}
        run:  |
              cmake -S ..
              cmake --build .

      - name: Linux binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.BUILD_DIR }}/**/${{ env.ARTIFACT }}
