name: Windows Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
    - 'main'

defaults:
  run:
    shell: cmd

env:
  BUILD_DIR:    ${{ github.workspace }}\build
  DEPLOY_DIR:    ${{ github.workspace }}\deploy
  QT_VERSION:   6.2.*

jobs:
  build:
    runs-on:  windows-2019

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version:      ${{ env.QT_VERSION }}
          host:         windows
          target:       desktop
          arch:         win64_msvc2019_64
          dir:          ${{ runner.temp }}
          setup-python: false

      - name: Create build directory
        run:  mkdir -p ${{ env.BUILD_DIR }}

      - name: Build
        working-directory: ${{ env.BUILD_DIR }}
        run:  |
              cmake -S ..
              cmake --build . --config Release
              windeployqt.exe --qmldir ${{ github.workspace }}\src\frontend ${{ env.BUILD_DIR }}\src\Debug\liv.exe --debug --compiler-runtime --dir ${{ env.DEPLOY_DIR }}

      - name: Prepare artifacts
        working-directory: ${{ github.workspace }}
        run:  copy ${{ env.BUILD_DIR }}\src\Debug\liv.exe ${{ env.DEPLOY_DIR }}
              copy C:\Windows\System32\concrt140.dll ${{ env.DEPLOY_DIR }}
              copy C:\Windows\System32\vccorlib140.dll ${{ env.DEPLOY_DIR }}
              copy C:\Windows\System32\msvcp140.dll ${{ env.DEPLOY_DIR }}
              copy C:\Windows\System32\vcruntime140.dll ${{ env.DEPLOY_DIR }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows executable
          path: ${{ github.workspace }}/deploy/
